#!/usr/bin/env bash
# Launch one configured resume command in a visible Windows terminal.
# The proxy passes a run id; all files below belong to that one runner only.
set -uo pipefail

PROJECT_PATH="${1:?missing project path}"
COMMAND="${2:?missing command}"
PID_FILE="${3:?missing pid file}"
STATUS_FILE="${4:?missing status file}"
TITLE="${5:-Codex Resume}"
CMD_PATH="${6:-/mnt/c/Windows/System32/cmd.exe}"
RUN_ID="${7:-legacy-$$}"
WSL_PATH="${CODEX_RESUME_WSL_PATH:-/mnt/c/Windows/System32/wsl.exe}"

# The run id is generated by proxy.js. Keep a conservative fallback for old
# callers so it can never inject arbitrary JSON into the local lease files.
if [[ ! "$RUN_ID" =~ ^[A-Za-z0-9._:-]{1,128}$ ]]; then
  RUN_ID="legacy-$$"
fi

# cmd.exe's `start` treats any leading "/" as a switch, so a POSIX path like
# /mnt/c/... must be converted to its Windows backslash form before `start`.
WSL_WIN_PATH="$WSL_PATH"
if [[ "$WSL_WIN_PATH" == /mnt/* ]]; then
  if command -v wslpath >/dev/null 2>&1; then
    WSL_WIN_PATH="$(wslpath -w "$WSL_WIN_PATH" 2>/dev/null || true)"
  fi
  if [[ -z "$WSL_WIN_PATH" || "$WSL_WIN_PATH" == /* ]]; then
    WSL_WIN_PATH="C:${WSL_PATH#/mnt/c}"
  fi
fi

atomic_write() {
  local target="$1"
  local content="$2"
  local temporary="${target}.tmp.$$"
  umask 077
  if printf '%s\n' "$content" > "$temporary" && mv -f -- "$temporary" "$target"; then
    return 0
  fi
  rm -f -- "$temporary"
  return 1
}

json_escape() {
  local value="${1-}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\r'/ }"
  value="${value//$'\n'/ }"
  value="${value//$'\t'/ }"
  printf '%s' "$value"
}

numeric_or_null() {
  if [[ "${1-}" =~ ^-?[0-9]+$ ]]; then
    printf '%s' "$1"
  else
    printf 'null'
  fi
}

started_at=0
command_pid=0

write_status() {
  local phase="$1"
  local pid="${2:-0}"
  local exit_code="${3:-}"
  local signal="${4:-}"
  local origin="${5:-runner}"
  local detail="${6:-}"
  local now
  now="$(date +%s)000"
  local pid_json exit_json signal_json origin_json detail_json
  pid_json="$(numeric_or_null "$pid")"
  exit_json="$(numeric_or_null "$exit_code")"
  signal_json="$(json_escape "$signal")"
  origin_json="$(json_escape "$origin")"
  detail_json="$(json_escape "$detail")"
  local payload
  payload="$(printf '{"schema":2,"phase":"%s","pid":%s,"updatedAt":%s,"exitCode":%s,"runId":"%s","startedAt":%s,"signal":"%s","origin":"%s","detail":"%s"}' \
    "$phase" "$pid_json" "$now" "$exit_json" "$RUN_ID" "$(numeric_or_null "$started_at")" "$signal_json" "$origin_json" "$detail_json")"
  atomic_write "$STATUS_FILE" "$payload" || true
}

write_lease() {
  local pid="$1"
  local pgid="$2"
  local created_at="$3"
  local start_ticks="$4"
  local payload
  payload="$(printf '{"schema":1,"runId":"%s","pid":%s,"pgid":%s,"createdAt":%s,"processStartTicks":%s}' \
    "$RUN_ID" "$(numeric_or_null "$pid")" "$(numeric_or_null "$pgid")" "$(numeric_or_null "$created_at")" "$(numeric_or_null "$start_ticks")")"
  atomic_write "$PID_FILE" "$payload" || true
}

read_proc_start_ticks() {
  local pid="$1"
  local line rest
  line="$(cat "/proc/$pid/stat" 2>/dev/null || true)"
  [ -n "$line" ] || return 0
  # After the final ") " the first field is stat field 3; field 22 is
  # therefore position 20 in the remaining whitespace-separated fields.
  rest="${line##*) }"
  set -- $rest
  printf '%s' "${20:-}"
}

RUNNER_FILE="$(mktemp /tmp/codex-resume-runner.XXXXXX)" || {
  write_status "launcher_failed" 0 1 "" "runner" "cannot create runner file"
  exit 1
}

write_runner_value() {
  printf '%s=%q\n' "$1" "$2"
}

{
  printf '%s\n' '#!/usr/bin/env bash'
  write_runner_value PROJECT_PATH "$PROJECT_PATH"
  write_runner_value COMMAND "$COMMAND"
  write_runner_value PID_FILE "$PID_FILE"
  write_runner_value STATUS_FILE "$STATUS_FILE"
  write_runner_value RUNNER_FILE "$RUNNER_FILE"
  write_runner_value RUN_ID "$RUN_ID"
  cat <<'RUNNER'
set -uo pipefail

atomic_write() {
  local target="$1"
  local content="$2"
  local temporary="${target}.tmp.$$"
  umask 077
  if printf '%s\n' "$content" > "$temporary" && mv -f -- "$temporary" "$target"; then
    return 0
  fi
  rm -f -- "$temporary"
  return 1
}

json_escape() {
  local value="${1-}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\r'/ }"
  value="${value//$'\n'/ }"
  value="${value//$'\t'/ }"
  printf '%s' "$value"
}

numeric_or_null() {
  if [[ "${1-}" =~ ^-?[0-9]+$ ]]; then printf '%s' "$1"; else printf 'null'; fi
}

signal_name() {
  case "${1-}" in
    1) printf 'HUP' ;;
    2) printf 'INT' ;;
    15) printf 'TERM' ;;
    *) printf 'SIG%s' "${1:-unknown}" ;;
  esac
}

command_pid=0
command_start_ticks=""
started_at=0

read_proc_start_ticks() {
  local pid="$1"
  local line rest
  line="$(cat "/proc/$pid/stat" 2>/dev/null || true)"
  [ -n "$line" ] || return 0
  rest="${line##*) }"
  set -- $rest
  printf '%s' "${20:-}"
}

write_status() {
  local phase="$1"
  local pid="${2:-0}"
  local exit_code="${3:-}"
  local signal="${4:-}"
  local origin="${5:-runner}"
  local detail="${6:-}"
  local now
  now="$(date +%s)000"
  local detail_json signal_json origin_json payload
  detail_json="$(json_escape "$detail")"
  signal_json="$(json_escape "$signal")"
  origin_json="$(json_escape "$origin")"
  payload="$(printf '{"schema":2,"phase":"%s","pid":%s,"updatedAt":%s,"exitCode":%s,"runId":"%s","startedAt":%s,"signal":"%s","origin":"%s","detail":"%s"}' \
    "$phase" "$(numeric_or_null "$pid")" "$now" "$(numeric_or_null "$exit_code")" "$RUN_ID" "$(numeric_or_null "$started_at")" "$signal_json" "$origin_json" "$detail_json")"
  atomic_write "$STATUS_FILE" "$payload" || true
}

write_lease() {
  local pid="$1"
  local pgid="$2"
  local created_at="$3"
  local start_ticks="$4"
  local payload
  payload="$(printf '{"schema":1,"runId":"%s","pid":%s,"pgid":%s,"createdAt":%s,"processStartTicks":%s}' \
    "$RUN_ID" "$(numeric_or_null "$pid")" "$(numeric_or_null "$pgid")" "$(numeric_or_null "$created_at")" "$(numeric_or_null "$start_ticks")")"
  atomic_write "$PID_FILE" "$payload" || true
}

cleanup() {
  rm -f -- "$PID_FILE" "$RUNNER_FILE"
}

terminate() {
  local signal="$1"
  local exit_code=143
  case "$signal" in
    HUP) exit_code=129 ;;
    INT) exit_code=130 ;;
    TERM) exit_code=143 ;;
  esac
  if [[ "$command_pid" =~ ^[0-9]+$ ]] && (( command_pid > 1 )) && [ -n "$command_start_ticks" ]; then
    current_start_ticks="$(read_proc_start_ticks "$command_pid")"
    if [ -n "$current_start_ticks" ] && [ "$current_start_ticks" = "$command_start_ticks" ]; then
      # setsid gives the command its own process group. Never fall back to a
      # bare PID kill: a reused PID must not target an unrelated process.
      kill -- "-$command_pid" 2>/dev/null || true
    fi
  fi
  write_status "terminated" "$command_pid" "$exit_code" "$signal" "runner_signal" "runner received $signal"
  exit "$exit_code"
}

trap cleanup EXIT
trap 'terminate HUP' HUP
trap 'terminate INT' INT
trap 'terminate TERM' TERM

if ! cd -- "$PROJECT_PATH"; then
  write_status "cd_failed" 0 1 "" "runner" "cannot enter project directory"
  exit 1
fi

started_at="$(date +%s)000"
write_status "starting" 0 "" "" "runner" "project directory ready"
# codex CLI resume is interactive and needs a PTY. Keep the PTY wrapper, but
# record its lifecycle separately from the Windows launcher return code.
if command -v script >/dev/null 2>&1; then
  setsid script -qec "$COMMAND" /dev/null &
else
  setsid bash -lc "$COMMAND" &
fi
command_pid=$!
start_ticks="$(read_proc_start_ticks "$command_pid")"
command_start_ticks="$start_ticks"
write_lease "$command_pid" "$command_pid" "$started_at" "$start_ticks"
write_status "running" "$command_pid" "" "" "runner" "command process started"

wait "$command_pid"
exit_code=$?
if (( exit_code == 0 )); then
  write_status "exited" "$command_pid" "$exit_code" "" "command" "command exited normally"
elif (( exit_code >= 128 && exit_code <= 192 )); then
  signal_number=$((exit_code - 128))
  signal_name_value="$(signal_name "$signal_number")"
  write_status "terminated" "$command_pid" "$exit_code" "$signal_name_value" "command_signal" "command exited from signal $signal_number"
else
  write_status "failed" "$command_pid" "$exit_code" "" "command" "command exited with failure"
fi
exit "$exit_code"
RUNNER
} > "$RUNNER_FILE"

chmod 700 "$RUNNER_FILE"
CMD_OUT="$( { "$CMD_PATH" /d /s /c start "$TITLE" "$WSL_WIN_PATH" bash -l "$RUNNER_FILE"; } 2>&1 )"
launcher_code=$?
if (( launcher_code != 0 )); then
  if [ -n "$CMD_OUT" ]; then
    CMD_OUT_MSG="$(printf '%s' "$CMD_OUT" | iconv -f GBK -t UTF-8//IGNORE 2>/dev/null || true)"
    [ -z "$CMD_OUT_MSG" ] && CMD_OUT_MSG="$CMD_OUT"
    CMD_OUT_MSG="$(printf '%s' "$CMD_OUT_MSG" | tr '\r\n\t' '   ' | tr -s ' ' | cut -c1-200)"
  else
    CMD_OUT_MSG="cmd.exe start returned $launcher_code"
  fi
  write_status "launcher_failed" 0 "$launcher_code" "" "cmd_start" "$CMD_OUT_MSG"
  rm -f -- "$RUNNER_FILE"
  exit "$launcher_code"
fi

# A zero exit code here means only that cmd.exe accepted the start request.
# The runner status file is the authoritative lifecycle source.
exit 0
